
GET http://localhost:3003/api/blogs
###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "One more time",
    "author": "Britney Spears",
    "url": "sdfmdlskfsdlf",
    "likes": 100
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "We could be heroes",
    "author": "David Bowie",
    "url": "sdfmdlskfsdlf",
    "likes": 300
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Zombie",
    "author": "Cranberries",
    "url": "lsdkfhdslkd",
    "likes": 120
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "You are enough",
    "author": "Zox",
    "url": "dsdfiodfmri",
    "likes": 40
}