
GET http://localhost:3003/api/blogs
###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "One more time",
    "author": "Britney Spears",
    "url": "sdfmdlskfsdlf",
    "likes": 100
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "We could be heroes",
    "author": "David Bowie",
    "url": "sdfmdlskfsdlf"
}
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Zombie",
    "author": "Cranberries",
    "url": "lsdkfhdslkd",
    "likes": 120
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "You are enough",
    "author": "Zox",
    "url": "dsdfiodfmri",
    "likes": 40
}
###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "url": "sdfmdlskfsdlf",
    "likes": 100
}
###
DELETE http://localhost:3003/api/blogs/611fb825d9e12c0c67387126

###
PUT http://localhost:3003/api/blogs/611ee52973200f0b2859da34
content-type: application/json

{
    "title": "Zombie",
    "author": "Miley",
    "url": "lsdkfhdslkd",
    "likes": 120
}
